### ISSUE TITLE
Not work for 💁🏻💁🏼💁🏽💁🏾💁🏿💁

### ISSUE THREAD

**Issue by dowenliu-xyz** [YvesCheung/EmojiReader#1]

**Comment by YvesCheung** [comment]
It's weird for this format:

**Comment by YvesCheung** [comment]
It's a weird format："\uD83D\uDC81\uD83C\uDFFB".
![image](https://user-images.githubusercontent.com/18024705/103122906-3c568b00-46bd-11eb-9c6f-0b8b55d4b0f5.png)
A combination of emoji and a color. I try to fix this problem today.

**Comment by YvesCheung** [comment]
Thanks!
45821b3ffaa42d733d1bf8ea3c34427e0f5f684b fix this problem.
Release v2.0.4

**Comment by YvesCheung** [comment]
![image](https://user-images.githubusercontent.com/18024705/103125997-e5a27e80-46c7-11eb-88c0-bad78457c1bc.png)
It's work now~
