### ISSUE TITLE
一些基础的emoji没有识别出来

### ISSUE THREAD

**Issue by ifontapp** [YvesCheung/EmojiReader#30]
例如⌚️ ⏰ ， 这些都算比较旧的emoji表情了，为啥会识别不出来呢

**Comment by YvesCheung** [comment]
我现在看一下

**Comment by YvesCheung** [comment]
0x231A..0x23FF码点段有几个漏网之鱼，已经修复： 9dc32c216e91d5412e627b329e8870cd7a42bece
预览：https://emoji-reader.vercel.app/

**Comment by ifontapp** [comment]
还有这些： ↗️  ↘️  ↙️  ↖️  ↔️  ⏩ ⏪   ⏫  ⏬

**Comment by YvesCheung** [comment]
⏩ ⏪ ⏫ ⏬  这四个能正常识别是Emoji。
其他的是非emoji线框+emoji修饰符变成了Emoji的情况。
修复： cc2fe011a6deadb075be1e515e03133dd1ed04c8
